### ISSUE TITLE
Switch to associating with the site's uid instead of id

### ISSUE THREAD

**Issue by JoshCoady** [eastslopestudio/craft-sites-field#8]
The site `id` is DB data. It would be preferable to not reference identifiers managed by the DB in the project.yaml config file because this creates the possibility of referencing data that does not exist or that is different (a different DB may associate a different site `id` with the same logical site depending on creation order). This is not really a problem when there is only one DB, but in situations where there is separate test site DBs or local dev DBs it is best to keep a distinction between config that is shared in the code repos and data in the DB.

The project.yaml file references sites by the site `uid`, so it would be better to store that as part of the field config instead.

This will be a breaking change for existing users of the plugin, so I did not want to just put up a quick PR for it as I am not familiar with writing migrations which would be needed to provide a safe upgrade path.

**Comment by ryanscherler** [comment]
I'm fine with going ahead and moving to `uid` - I can tag this release and users can upgrade with a warning that this is a breaking change (or just stick with the current version and upgrade when they want to?)
